<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Pulumi.Automation" Version="3.106.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LiveArch.Deployment.Azure\LiveArch.Deployment.Azure.csproj" />
    <ProjectReference Include="..\LiveArch.Deployment\LiveArch.Deployment.csproj" />
    <ProjectReference Include="..\LiveArch.Diagram\LiveArch.Diagram.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net10.0\.pulumi\state\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net10.0\.pulumi\secret">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
