graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Deployment View: ${ENV}"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 41 ["Sandbox"]
      style 41 fill:#ffffff,stroke:#444444,color:#444444

      42["<div style='font-weight: bold'>Test Storage Account</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: azure-native:storage:StorageAccount]</div>"]
      style 42 fill:#ffffff,stroke:#444444,color:#444444
      43["<div style='font-weight: bold'>Test Managed Identity</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: azure-native:managedidentity:UserAssignedIdentity]</div>"]
      style 43 fill:#ffffff,stroke:#444444,color:#444444
    end

    43-. "<div>Contribute</div><div style='font-size: 70%'>[azure-native:authorization:RoleAssignment]</div>" .->42

  end