graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Container View: Order Microservice"]
    style diagram fill:#ffffff,stroke:#ffffff

    1["<div style='font-weight: bold'>Message Broker</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div>"]
    style 1 fill:#ffffff,stroke:#444444,color:#444444

    subgraph 6 ["Order Microservice"]
      style 6 fill:#ffffff,stroke:#444444,color:#444444

      14["<div style='font-weight: bold'>Order Worker</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:web:WebApp]</div>"]
      style 14 fill:#ffffff,stroke:#444444,color:#444444
      7["<div style='font-weight: bold'>Order Database</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:sql:Database]</div>"]
      style 7 fill:#ffffff,stroke:#444444,color:#444444
      8["<div style='font-weight: bold'>Order API</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:web:WebApp]</div>"]
      style 8 fill:#ffffff,stroke:#444444,color:#444444
    end

    8-. "<div>publish Order Placed Message</div><div style='font-size: 70%'></div>" .->1
    14-. "<div>uses</div><div style='font-size: 70%'></div>" .->7
    14-. "<div>consume Delivery Completed<br />Message</div><div style='font-size: 70%'>[azurela:servicebus:ReadableSubscription]</div>" .->1
    8-. "<div>uses</div><div style='font-size: 70%'></div>" .->7

  end