graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Deployment View: ${ENV}"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 37 ["Shared Resource Group Reference"]
      style 37 fill:#ffffff,stroke:#444444,color:#444444

      subgraph 38 ["Service Bus Namespace"]
        style 38 fill:#ffffff,stroke:#444444,color:#444444

        39["<div style='font-weight: bold'>Order Events</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:servicebus:getTopic]</div>"]
        style 39 fill:#ffffff,stroke:#444444,color:#444444
        40["<div style='font-weight: bold'>Delivery Events</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:servicebus:getTopic]</div>"]
        style 40 fill:#ffffff,stroke:#444444,color:#444444
      end

    end

    subgraph 45 ["Order Resource Group"]
      style 45 fill:#ffffff,stroke:#444444,color:#444444

      subgraph 46 ["SQL Server Registration"]
        style 46 fill:#ffffff,stroke:#444444,color:#444444

        subgraph 47 ["SQL Server"]
          style 47 fill:#ffffff,stroke:#444444,color:#444444

          subgraph 48 ["Elastic Pool"]
            style 48 fill:#ffffff,stroke:#444444,color:#444444

            49["<div style='font-weight: bold'>Order Database</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:sql:Database]</div>"]
            style 49 fill:#ffffff,stroke:#444444,color:#444444
          end

        end

      end

      50["<div style='font-weight: bold'>Key Vault</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: azure-native:keyvault:getVault]</div>"]
      style 50 fill:#ffffff,stroke:#444444,color:#444444
      subgraph 51 ["Virtual Network"]
        style 51 fill:#ffffff,stroke:#444444,color:#444444

        subgraph 52 ["App Service Plan"]
          style 52 fill:#ffffff,stroke:#444444,color:#444444

          53["<div style='font-weight: bold'>Order API</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:web:WebApp]</div>"]
          style 53 fill:#ffffff,stroke:#444444,color:#444444
          56["<div style='font-weight: bold'>Order Worker</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:web:WebApp]</div>"]
          style 56 fill:#ffffff,stroke:#444444,color:#444444
        end

      end

      59["<div style='font-weight: bold'>Managed Identity</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: azure-native:managedidentity:UserAssignedIdentity]</div>"]
      style 59 fill:#ffffff,stroke:#444444,color:#444444
      62["<div style='font-weight: bold'>Storage Accounts</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: azure-native:appconfiguration:getKeyValue]</div>"]
      style 62 fill:#ffffff,stroke:#444444,color:#444444
      subgraph 63 ["Foreach Storage Account in Config"]
        style 63 fill:#ffffff,stroke:#444444,color:#444444

        64["<div style='font-weight: bold'>Source</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: foreach:source]</div>"]
        style 64 fill:#ffffff,stroke:#444444,color:#444444
        66["<div style='font-weight: bold'>Storage Account</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: azure-native:storage:getStorageAccount]</div>"]
        style 66 fill:#ffffff,stroke:#444444,color:#444444
      end

      68["<div style='font-weight: bold'>Key Vault Access Policy</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: azure-native:keyvault:AccessPolicy]</div>"]
      style 68 fill:#ffffff,stroke:#444444,color:#444444
    end

    53-. "<div>publish Order Placed Message</div><div style='font-size: 70%'></div>" .->39
    53-. "<div>uses</div><div style='font-size: 70%'></div>" .->49
    56-. "<div>subscribe to Delivery<br />Completed Message</div><div style='font-size: 70%'>[azurela:servicebus:ReadableSubscription]</div>" .->40
    56-. "<div>uses</div><div style='font-size: 70%'></div>" .->49
    53-. "<div>identity</div><div style='font-size: 70%'></div>" .->59
    56-. "<div>identity</div><div style='font-size: 70%'></div>" .->59
    64-. "<div>take</div><div style='font-size: 70%'></div>" .->62
    59-. "<div>Contribute</div><div style='font-size: 70%'>[azure-native:authorization:RoleAssignment]</div>" .->66
    68-. "<div>principal</div><div style='font-size: 70%'></div>" .->59
    68-. "<div>vault</div><div style='font-size: 70%'></div>" .->50

  end