graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["System Context View: Order Microservice"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph group1 ["Ordering"]
      style group1 fill:#ffffff,stroke:#cccccc,color:#cccccc,stroke-dasharray:5

      5["<div style='font-weight: bold'>Order Microservice</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div>"]
      style 5 fill:#ffffff,stroke:#444444,color:#444444
    end

    1["<div style='font-weight: bold'>Order Messaging System</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div>"]
    style 1 fill:#ffffff,stroke:#444444,color:#444444
    3["<div style='font-weight: bold'>Delivery Messaging System</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div>"]
    style 3 fill:#ffffff,stroke:#444444,color:#444444

    5-. "<div>publish Order Placed Message</div><div style='font-size: 70%'></div>" .->1
    5-. "<div>subscribe to Delivery<br />Completed Message</div><div style='font-size: 70%'>[azurela:servicebus:ReadableSubscription]</div>" .->3

  end