graph LR
  linkStyle default fill:#ffffff

  subgraph diagram ["Component View: Message Broker - Delivery Events"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 1 ["Message Broker"]
      style 1 fill:#ffffff,stroke:#444444,color:#444444

      subgraph 4 ["Delivery Events"]
        style 4 fill:#ffffff,stroke:#444444,color:#444444

        5["<div style='font-weight: bold'>Delivery Completed Message</div><div style='font-size: 70%; margin-top: 0px'>[Component: message]</div>"]
        style 5 fill:#ffffff,stroke:#444444,color:#444444
      end

    end

  end