graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["System Context View: Delivery Microservice"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph group1 ["Delivery"]
      style group1 fill:#ffffff,stroke:#cccccc,color:#cccccc,stroke-dasharray:5

      19["<div style='font-weight: bold'>Delivery Microservice</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div>"]
      style 19 fill:#ffffff,stroke:#444444,color:#444444
    end

    1["<div style='font-weight: bold'>Order Messaging System</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div>"]
    style 1 fill:#ffffff,stroke:#444444,color:#444444
    3["<div style='font-weight: bold'>Delivery Messaging System</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div>"]
    style 3 fill:#ffffff,stroke:#444444,color:#444444

    19-. "<div>publish Delivery Events</div><div style='font-size: 70%'></div>" .->3
    19-. "<div>subscribe to Order Placed<br />Message</div><div style='font-size: 70%'>[azurela:servicebus:ReadableSubscription]</div>" .->1

  end