graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Deployment View: ${ENV}"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 37 ["Shared Resource Group Reference"]
      style 37 fill:#ffffff,stroke:#444444,color:#444444

      subgraph 38 ["Service Bus Namespace"]
        style 38 fill:#ffffff,stroke:#444444,color:#444444

        39["<div style='font-weight: bold'>Order Events</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:servicebus:getTopic]</div>"]
        style 39 fill:#ffffff,stroke:#444444,color:#444444
        40["<div style='font-weight: bold'>Delivery Events</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:servicebus:getTopic]</div>"]
        style 40 fill:#ffffff,stroke:#444444,color:#444444
      end

    end

    subgraph 71 ["Delivery Resource Group"]
      style 71 fill:#ffffff,stroke:#444444,color:#444444

      subgraph 72 ["SQL Server Registration"]
        style 72 fill:#ffffff,stroke:#444444,color:#444444

        subgraph 73 ["SQL Server"]
          style 73 fill:#ffffff,stroke:#444444,color:#444444

          subgraph 74 ["Elastic Pool"]
            style 74 fill:#ffffff,stroke:#444444,color:#444444

            75["<div style='font-weight: bold'>Delivery Database</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:sql:Database]</div>"]
            style 75 fill:#ffffff,stroke:#444444,color:#444444
          end

        end

      end

      76["<div style='font-weight: bold'>Key Vault</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: azure-native:keyvault:getVault]</div>"]
      style 76 fill:#ffffff,stroke:#444444,color:#444444
      77["<div style='font-weight: bold'>Managed Identity</div><div style='font-size: 70%; margin-top: 0px'>[Infrastructure Node: azure-native:managedidentity:UserAssignedIdentity]</div>"]
      style 77 fill:#ffffff,stroke:#444444,color:#444444
      subgraph 79 ["Virtual Network"]
        style 79 fill:#ffffff,stroke:#444444,color:#444444

        subgraph 80 ["App Service Plan"]
          style 80 fill:#ffffff,stroke:#444444,color:#444444

          81["<div style='font-weight: bold'>Delivery API</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:web:WebApp]</div>"]
          style 81 fill:#ffffff,stroke:#444444,color:#444444
          85["<div style='font-weight: bold'>Delivery Worker</div><div style='font-size: 70%; margin-top: 0px'>[Container: azure-native:web:WebApp]</div>"]
          style 85 fill:#ffffff,stroke:#444444,color:#444444
        end

      end

    end

    77-. "<div>reads</div><div style='font-size: 70%'>[azure-native:keyvault:AccessPolicy]</div>" .->76
    81-. "<div>publish Delivery Events</div><div style='font-size: 70%'></div>" .->40
    81-. "<div>uses</div><div style='font-size: 70%'></div>" .->75
    81-. "<div>identity</div><div style='font-size: 70%'></div>" .->77
    85-. "<div>subscribe to Order Placed<br />Message</div><div style='font-size: 70%'>[azurela:servicebus:ReadableSubscription]</div>" .->39
    85-. "<div>uses</div><div style='font-size: 70%'></div>" .->75
    85-. "<div>identity</div><div style='font-size: 70%'></div>" .->77

  end